---
- name: Create the temporary u-c file
  tempfile:
    state: file
    suffix: u-c
  register: u_c_file

- name: Download u-c
  get_url:
    url: "{{ sushy_python_upper_constraints_url }}"
    dest: "{{ u_c_file.path }}"
    mode: "0644"
  register: result
  until: result is success
  retries: 3

- name: Remove libvirt-python from u-c
  lineinfile:
    path: "{{ u_c_file.path }}"
    state: absent
    regexp: '^libvirt-python'

- name: Ensure Python requirements are installed
  pip:
    name: sushy-tools
    extra_args: -c {{ u_c_file.path }}
    virtualenv: "{{ sushy_tools_virtualenv_path }}"
  register: result
  until: result is success
  retries: 3

- name: Remove the temporary u-c file
  file:
    path: "{{ u_c_file.path }}"
    state: absent

- name: "[selinux] Allow systemd to start sushy-emulator from venv"
  when:
    - ansible_facts.selinux.status | default('disabled') == 'enabled'
    - sushy_tools_virtualenv_path
  block:

    - name: "[selinux] Allow systemd to start sushy-emulator from venv - sefcontext"
      become: true
      sefcontext:
        target: "{{ sushy_tools_virtualenv_path }}/bin(/.*)?"
        setype: bin_t
        state: present
      register: sefcontext

    - name: "[selinux] Allow systemd to start sushy-emulator from venv - restorecon"  # noqa no-handler
      become: true
      command: "restorecon -r {{ sushy_tools_virtualenv_path }}/bin"
      when: sefcontext.changed
      changed_when: true

- name: Ensure the Sushy emulator is configured
  template:
    src: templates/sushy_emulator.conf.j2
    dest: "{{ sushy_emulator_conf_path }}"
    mode: "0666"
  register: conf_file

- name: Ensure Sushy emulator systemd service is configured
  template:
    src: templates/sushy_emulator.service.j2
    dest: /etc/systemd/system/sushy_emulator.service
    owner: root
    group: root
    mode: "0644"
  become: true
  register: service_file

- name: Ensure Sushy emulator systemd service is started and enabled
  systemd:
    name: sushy_emulator.service
    enabled: true
    state: restarted
    daemon_reload: "{{ service_file.changed }}"
  become: true
