---
- project:
    templates:
      - openstack-cover-jobs
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-py39:
            override-checkout: stable/2025.1
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-bios-centos9s:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-ovs-bios-rocky-9:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-linuxbridge-uefi-centos9s:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-linuxbridge-uefi-rocky-9:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-ovs-bios-centos10
        - tenks-deploy-teardown-linuxbridge-uefi-centos10
        - tenks-deploy-teardown-ovs-bios-debian-bookworm
        - tenks-deploy-teardown-linuxbridge-uefi-debian-bookworm
        - tenks-deploy-teardown-ovs-bios-ubuntu-noble
        - tenks-deploy-teardown-linuxbridge-uefi-ubuntu-noble
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        - kayobe-overcloud-rocky9:
            voting: false
        - tenks-tox-codespell:
            voting: false
    gate:
      jobs:
        - openstack-tox-py39:
            override-checkout: stable/2025.1
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-bios-centos9s:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-ovs-bios-rocky-9:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-linuxbridge-uefi-centos9s:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-linuxbridge-uefi-rocky-9:
            override-checkout: stable/2025.1
        - tenks-deploy-teardown-ovs-bios-centos10
        - tenks-deploy-teardown-linuxbridge-uefi-centos10
        - tenks-deploy-teardown-ovs-bios-debian-bookworm
        - tenks-deploy-teardown-linuxbridge-uefi-debian-bookworm
        - tenks-deploy-teardown-ovs-bios-ubuntu-noble
        - tenks-deploy-teardown-linuxbridge-uefi-ubuntu-noble
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        # - kayobe-overcloud-rocky9
