---
- project:
    templates:
      - openstack-python3-ussuri-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

    check:
      jobs:
        - openstack-tox-cover:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/train
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/train
        - openstack-tox-py27:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/train
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-centos
        - tenks-deploy-teardown-ubuntu
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        # FIXME(mgoddard): Kayobe CentOS 7 jobs no longer working. Replace with C8.
        # - kayobe-overcloud-centos
    gate:
      queue: tenks
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/train
        - openstack-tox-py27:
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/train
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-centos
        - tenks-deploy-teardown-ubuntu
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        # FIXME(mgoddard): Kayobe CentOS 7 jobs no longer working. Replace with C8.
        # - kayobe-overcloud-centos
