---
- project:
    templates:
      - openstack-cover-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3

    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-bios-centos9s
        - tenks-deploy-teardown-ovs-bios-debian-bullseye
        - tenks-deploy-teardown-ovs-bios-rocky-9
        - tenks-deploy-teardown-ovs-bios-ubuntu-jammy
        - tenks-deploy-teardown-linuxbridge-uefi-centos9s
        - tenks-deploy-teardown-linuxbridge-uefi-debian-bullseye
        - tenks-deploy-teardown-linuxbridge-uefi-rocky-9
        - tenks-deploy-teardown-linuxbridge-uefi-ubuntu-jammy
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        - kayobe-overcloud-rocky9:
            voting: false
        - kayobe-overcloud-ubuntu-jammy
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-py39
        - openstack-tox-py310
        - openstack-tox-py311
        - openstack-tox-py312
        - tenks-tox-ansible-lint
        - tenks-deploy-teardown-ovs-bios-centos9s
        - tenks-deploy-teardown-ovs-bios-debian-bullseye
        - tenks-deploy-teardown-ovs-bios-rocky-9
        - tenks-deploy-teardown-ovs-bios-ubuntu-jammy
        - tenks-deploy-teardown-linuxbridge-uefi-centos9s
        - tenks-deploy-teardown-linuxbridge-uefi-debian-bullseye
        - tenks-deploy-teardown-linuxbridge-uefi-rocky-9
        - tenks-deploy-teardown-linuxbridge-uefi-ubuntu-jammy
        # Until we have ironic jobs using tenks, gate on the kayobe overcloud
        # deploy job, which uses tenks to test bare metal compute provisioning.
        # - kayobe-overcloud-rocky9
        - kayobe-overcloud-ubuntu-jammy
