---
- block:
    # NOTE(mgoddard): The CentOS image used in CI has epel-release installed,
    # but the configure-mirrors role used by Zuul disables epel. Since we
    # install epel-release and expect epel to be enabled, enable it here.
    - name: Ensure yum-utils is installed
      yum:
        name: yum-utils
        state: installed

    - name: Enable the EPEL yum repository
      command: yum-config-manager --enable epel
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install Python2 modules
  become: true
  package:
    name:
      - python-pip
      - python-setuptools
      - python-virtualenv
      - python-wheel
  when: ansible_os_family == 'RedHat'

- name: Install Python3 modules
  become: true
  package:
    name:
      - python3-pip
      - python3-setuptools
      - python3-virtualenv
      - python3-wheel
      - virtualenv
  when: ansible_os_family == 'Debian'

- name: Ensure latest pip is installed
  become: true
  pip:
    name: pip
    state: latest
